[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pymassbank"
version = "0.0.2"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "rdflib",
]

[project.urls]
Homepage = "https://github.com/systemsomicslab/pymassbank"
Issues = "https://github.com/systemsomicslab/pymassbank/issues"
